name: Development Builds

on:
  push:
    branches: ["develop"]

jobs:
  build_cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: cd gui; mkdir bin; go build -o bin/snes2c64-cli-linux-amd64 snes2c64gui/cmd/cli

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: cli-binary
          path: gui/bin/
  build_gui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Get dependencies
        run: sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev libwayland-dev libxkbcommon-dev bc
        if: ${{ runner.os == 'Linux' }}

      - name: Build
        run: cd gui; mkdir bin; go build -o bin/snes2c64-gui-linux-amd64 snes2c64gui/cmd/gui

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: gui-binary
          path: gui/bin/
  release:
    runs-on: ubuntu-latest
    needs: [build_cli, build_gui]
    steps:
      - name: Download cli binary
        uses: actions/download-artifact@v3
        with:
          name: cli-binary
          path: gui/bin/
      - name: Download gui binary
        uses: actions/download-artifact@v3
        with:
          name: gui-binary
          path: gui/bin/
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest build on develop"
          files: |
            gui/bin/snes2c64-cli-linux-amd64
            gui/bin/snes2c64-gui-linux-amd64
