name: Development Builds

on:
  push:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: cd gui; go build -o snes2c64-cli-linux-amd64 snes2c64gui/cmd/cli

      - name: Test
        run: cd gui; go test -v ./...

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest build on develop"
          files: |
            snes2c64-cli-linux-amd64
